### ISSUE TITLE
How to use this language server?

### ISSUE THREAD

**Issue by ghost** [AdeptLanguage/AdeptLSP#1]
For example, how to setup SublimeText to use it?

**Comment by IsaacShelton** [comment]
It's not complete yet, so is unusable at the moment.

Eventually though it should be pretty easy to setup I think, SublimeText probably has a built-in LSP client than can be connected to it.

**Comment by IsaacShelton** [comment]
@iahung2 A basic version is now available, you can test it by following the instructions in README.md

It currently supports hovering and basic auto-completion.

![Screenshot 2024-02-07 at 9 53 26 PM](https://github.com/AdeptLanguage/AdeptLSP/assets/14429506/0d6af10f-c5c3-4f51-bdcb-9040b8b92ff7)
